spring:
  application:
    name: microservice-movie
server:
  port: 9003
eureka:
  client:
    register-with-eureka: true #作为客户端需要注册到eureka
    fetch-registry: true #作为客户端需要从eureka获取注册信息
    service-url:  #客户端注册地址
      defaultZone: http://127.0.0.1:8888/eureka,http://127.0.0.1:9999/eureka
    #修改提供方获取注册信息的间隔时间
    registry-fetch-interval-seconds: 10

  instance:
    prefer-ip-address: true #优先使用该服务的ip地址注册到eureka，在实际生产环境中建议为true
#开启hystrix
feign:
  hystrix:
    enabled: true